// Templates from the supplied SaintFlow vault (2026-09-22).
import type { CreatableType } from "./model";

export const DEFAULT_TEMPLATES: Record<CreatableType, string> = {
	"task": "---\ntype: task\nstatus: next\nproject:\narea:\nparent:\nscheduled:\ndue:\nwaiting_on:\nlink:\narchived: false\ncreated: \"{{date:YYYY-MM-DD}}\"\n---\n%% 끝났을 때의 모습을 한 줄로 적습니다. 한자리에서 끝나는 단계는 하위 Task로, 여러 날에 걸치거나 결과물이 따로 나오면 Project로 올립니다. %%\n\n## 하위 Task\n![[Tasks.base#연결됨]]\n%% 이 노트에서 SF 새 항목 → 하위 Task. 모두 끝나면 하위 진행에 ✓가 붙고, 이 Task의 status는 직접 done으로 바꿉니다. %%\n\n## 메모\n",
	"project": "---\ntype: project\nstatus: active\ndone_criteria:\ndue:\narea:\nparent:\nrepo:\nlink:\narchived: false\ncreated: \"{{date:YYYY-MM-DD}}\"\n---\n> [!sf-evidence] 완료 조건 먼저\n> 끝났다고 판정할 수 있는 한 문장을 `done_criteria`에 적습니다. active인 동안 next · in progress · waiting 상태의 Task나 active 하위 프로젝트가 하나 이상 있어야 합니다. 시작 전이면 planned, 잠시 멈추면 paused로 둡니다.\n\n## 목표\n\n## 다음 행동\n![[Tasks.base#연결됨]]\n\n## 하위 프로젝트\n![[Projects.base#연결됨]]\n\n## 결과물\n![[Outputs.base#연결됨]]\n\n## 자료와 지식\n![[Resources.base#연결됨]]\n![[Knowledge.base#연결됨]]\n\n## 결정 기록\n- YYYY-MM-DD — 결정과 이유\n\n## 작업 노트\n%% 조사, 비교, 초안은 여기에 씁니다. 길어지면 별도 노트로 떼고 project 속성에 이 프로젝트를 연결합니다. %%\n",
	"area": "---\ntype: area\nstatus: active\nstandard:\nreview_cycle: 매월\nlink:\narchived: false\ncreated: \"{{date:YYYY-MM-DD}}\"\n---\n> [!sf-evidence] 유지 기준\n> 무엇이 유지되면 괜찮은지 한 문장으로 `standard`에 적고, `review_cycle`을 정합니다.\n\n## 책임 범위\n\n## 프로젝트\n![[Projects.base#연결됨]]\n\n## Task\n![[Tasks.base#연결됨]]\n\n## 자료와 지식\n![[Resources.base#연결됨]]\n![[Knowledge.base#연결됨]]\n\n## 점검 기록\n- YYYY-MM-DD — 상태와 조치\n",
	"resource": "---\ntype: resource\nstatus: to read\nkind:\nauthor:\nlink:\nproject:\narea:\narchived: false\ncreated: \"{{date:YYYY-MM-DD}}\"\n---\n%% 원문 위치는 link, author, kind에 둡니다. 처리 단계는 status로 표시합니다: to read → reading → processed, 찾아보기만 할 자료는 reference. %%\n\n## 요약\n%% 세 줄 이내 %%\n\n## 발췌\n- p. 00 또는 00:00 — 내용\n\n## 여기서 나온 생각\n![[Knowledge.base#연결됨]]\n%% 이 노트에서 SF 새 항목 → Zettel로 만들면 source가 이 자료로 기록됩니다. %%\n",
	"zettel": "---\ntype: zettel\nmaturity: seed\nsource:\nproject:\narea:\nrecall: false\nquestion:\nbox: 1\nlast_reviewed:\nlast_result:\nlink:\narchived: false\ncreated: \"{{date:YYYY-MM-DD}}\"\n---\n%% 원문을 닫고 자기 말로 씁니다. 제목은 주장 한 문장입니다. %%\n\n## 생각\n\n## 근거\n\n## 적용 조건과 한계\n\n## 연결\n%% 한 줄에 하나씩: - [[대상]] — 연결한 이유 %%\n",
	"map": "---\ntype: map\narchived: false\ncreated: \"{{date:YYYY-MM-DD}}\"\n---\n%% 개념 하나를 중심에 두고 관련 Zettel을 배치합니다. 이 노트에서 SF 새 항목으로 만든 Zettel은 구조 섹션에 자동으로 추가됩니다. %%\n\n## 구조\n\n## 빈 곳\n%% 아직 Zettel이 없는 하위 개념 %%\n",
	"output": "---\ntype: output\nkind:\nstatus: draft\nproject:\nuses:\nlink:\narchived: false\ncreated: \"{{date:YYYY-MM-DD}}\"\n---\n> [!sf-evidence] done · shipped로 바꿀 때\n> 사용한 지식과 자료를 `uses`에 연결합니다. 비어 있으면 Weekly 점검에 나타납니다.\n\n## 요약\n\n## 지식에서 가져온 것\n%% - [[Zettel]] — 어디에 썼는가 %%\n\n## 위치\n%% 최종본 주소는 link에 둡니다. %%\n",
	"recall": "---\ntype: recall\ndate: \"{{date:YYYY-MM-DD}}\"\n---\n%% Zettel을 열기 전에 씁니다. 다 쓴 뒤 SF 회상 판정으로 판정합니다. 보통은 SF 회상 시작이 이 노트를 만들어 줍니다. %%\n\n## 판정\n",
	"daily": "---\ntype: daily\ndate: \"{{date:YYYY-MM-DD}}\"\n---\n- [ ] 다음 행동·예정·마감을 보고 오늘 할 일을 고른다\n- [ ] 오늘 회상을 처리한다\n- [ ] 새로 생긴 것을 수집한다\n\n## 오늘 할 일\n\n## 메모\n",
	"weekly": "---\ntype: weekly\ndate: \"{{date:YYYY-MM-DD}}\"\n---\n- [ ] 머리 비우기 질문으로 빠진 것을 수집한다\n- [ ] 0_Sweep을 0건으로 비운다\n- [ ] waiting 항목을 확인한다\n- [ ] 멈춘 프로젝트에 다음 행동을 정하고, planned · paused 프로젝트는 시작하거나 재개할지 정한다\n- [ ] 연결 없는 Zettel과 오래된 seed를 정리한다\n- [ ] 지식이 연결되지 않은 결과물의 uses를 채운다\n- [ ] someday 목록에서 활성화할 것을 고른다\n- [ ] 점검 주기가 된 영역을 본다\n\n점검 보기는 [[5_Flow|Flow]]에 있습니다.\n\n## 이번 주\n\n## 다음 주 초점\n",
	"closing": "---\ntype: closing\nproject:\ndate: \"{{date:YYYY-MM-DD}}\"\n---\n- [ ] 완료 조건을 판정한다\n- [ ] 재사용할 내용을 Knowledge와 Resources로 올린다\n- [ ] Outputs의 uses에 사용한 지식과 자료를 연결한다\n- [ ] 작업 노트에서 남길 것과 버릴 것을 가른다\n- [ ] 프로젝트 status를 done으로 바꾸고 archived를 켠다\n\n## 결과\n\n## 배운 것\n\n## 재사용할 것\n",
	"working": "---\ntype: working\nproject:\narea:\narchived: false\ncreated: \"{{date:YYYY-MM-DD}}\"\n---\n\n## 내용\n"
};
